"""TS-generated test fixtures for cross-implementation compatibility testing.

These fixtures are generated by TypeScript implementation and used to verify
that Python implementation produces identical results.

Reference: go-wallet-toolbox/pkg/internal/testabilities/tsgenerated/
"""

from .create_action_result import (
    CREATE_ACTION_RESULT,
    create_action_result_json,
    load_create_action_result,
)
from .signed_transaction import (
    SIGNED_TRANSACTION_HEX,
    signed_transaction,
    signed_transaction_bytes,
)
from .beef_to_internalize import (
    PARENT_BEEF,
    PARENT_BEEF_TXID,
    BEEF_TO_INTERNALIZE_HEIGHT,
    BEEF_TO_INTERNALIZE_MERKLE_ROOT,
    parent_transaction_atomic_beef,
)

__all__ = [
    # CreateActionResult
    "CREATE_ACTION_RESULT",
    "create_action_result_json",
    "load_create_action_result",
    # SignedTransaction
    "SIGNED_TRANSACTION_HEX",
    "signed_transaction",
    "signed_transaction_bytes",
    # BEEF to internalize
    "PARENT_BEEF",
    "PARENT_BEEF_TXID",
    "BEEF_TO_INTERNALIZE_HEIGHT",
    "BEEF_TO_INTERNALIZE_MERKLE_ROOT",
    "parent_transaction_atomic_beef",
]
